//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a filter to the current view, if supported..
        /// </summary>
        internal static string Filter_Description {
            get {
                return ResourceManager.GetString("Filter.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays this help dialog..
        /// </summary>
        internal static string Help_Description {
            get {
                return ResourceManager.GetString("Help.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Commands.
        /// </summary>
        internal static string HelpDialog_GlobalCommands {
            get {
                return ResourceManager.GetString("HelpDialog.GlobalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands available in all views.
        /// </summary>
        internal static string HelpDialog_GlobalCommandsDescription {
            get {
                return ResourceManager.GetString("HelpDialog.GlobalCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Press shortcut to view description].
        /// </summary>
        internal static string HelpDialog_ShortcutDescription {
            get {
                return ResourceManager.GetString("HelpDialog.ShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallPlugins {
            get {
                return ResourceManager.GetString("InstallPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and install available online plugins from
        ///nuget.org tagged with &apos;guit&apos;..
        /// </summary>
        internal static string InstallPlugins_Description {
            get {
                return ResourceManager.GetString("InstallPlugins.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse, enable, disable and install plugins..
        /// </summary>
        internal static string Plugins_Description {
            get {
                return ResourceManager.GetString("Plugins.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes the current view, if supported..
        /// </summary>
        internal static string Refresh_Description {
            get {
                return ResourceManager.GetString("Refresh.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePlugins {
            get {
                return ResourceManager.GetString("SavePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the changes to the installed plugins..
        /// </summary>
        internal static string SavePlugins_Description {
            get {
                return ResourceManager.GetString("SavePlugins.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects all items in the current view, if supported..
        /// </summary>
        internal static string SelectAll_Description {
            get {
                return ResourceManager.GetString("SelectAll.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next View.
        /// </summary>
        internal static string ShowNextView {
            get {
                return ResourceManager.GetString("ShowNextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the next view..
        /// </summary>
        internal static string ShowNextView_Description {
            get {
                return ResourceManager.GetString("ShowNextView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous View.
        /// </summary>
        internal static string ShowPreviousView {
            get {
                return ResourceManager.GetString("ShowPreviousView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the previous view..
        /// </summary>
        internal static string ShowPreviousView_Description {
            get {
                return ResourceManager.GetString("ShowPreviousView.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        internal static string Sync_Pull {
            get {
                return ResourceManager.GetString("Sync.Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views the currently selected item, opening it in
        ///the appropriate editor..
        /// </summary>
        internal static string View_Description {
            get {
                return ResourceManager.GetString("View.Description", resourceCulture);
            }
        }
    }
}
